### ISSUE TITLE
The footer is not properly aligned

### ISSUE THREAD

**Issue by chawlaaditya8** [Mozpacers/Mozpacers.github.io#27]
![screenshot from 2015-10-18 19 36 55](https://cloud.githubusercontent.com/assets/9032537/10564408/c31382c4-75d0-11e5-919d-ea2b74cf7b29.png)

The footer should be at the bottom of the page

**Comment by handasolo** [comment]
Almost fixed

**Comment by handasolo** [comment]
@chawlaaditya8 Fix has been deployed @chawlaaditya8 @CuriousLearner check if there's anything left, if not consider closing this.
