### ISSUE TITLE
CSS of date

### ISSUE THREAD

**Issue by chawlaaditya8** [Mozpacers/Mozpacers.github.io#28]
On hovering on the third event card the text is not properly aligned.
A screenshot to explain it better.
![screenshot from 2015-10-18 19 33 05](https://cloud.githubusercontent.com/assets/9032537/10564442/50ce7398-75d2-11e5-823c-afeb2ee91ea3.png)

**Comment by CuriousLearner** [comment]
Hi @chawlaaditya8!

Yes, the whole styling is needed to be done. That's happening on the third event specifically because the first two event have titles which occupies more space and are date is thus pushed to next line.

You can work on this. Just let us know if you're interested.

**Comment by handasolo** [comment]
Self assigning. Almost have been fixed.

**Comment by handasolo** [comment]
@CuriousLearner @chawlaaditya8 If you find this satisfactory, please close this.
