### ISSUE TITLE
Bug with Hash

### ISSUE THREAD

**Issue by handasolo** [Mozpacers/Mozpacers.github.io#35]
There's this bug I've encountered which I'm sure is because of my code. The bug can be reproduced as follows:
Type this in your browser 'http://mozpacers.org/#contact_form' and press enter. 
![screenshot from 2015-10-25 18 46 43](https://cloud.githubusercontent.com/assets/5322472/10715805/8b6627ea-7b49-11e5-9d0b-5006f0b7f3b9.png)
You'll see that it opens the interface that is meant to display more events or more information about events. This is true for any other hash you type as well. The problem here is that, I wrote code which scans what the hash is after opening this interface, so it should be fairly simple to correct.
Another part of this bug is when you're on the website itself, try to add the hash '#future-more' to it and press enter. It should lead to the interface, but it doesn't.
![screenshot from 2015-10-25 18 45 11](https://cloud.githubusercontent.com/assets/5322472/10715814/da8fc6e6-7b49-11e5-8533-4554624f1689.png)
Anyone who is interested in picking this, let us know.

**Comment by handasolo** [comment]
@CuriousLearner Check if this is still an issue?

**Comment by CuriousLearner** [comment]
Seems resolved. Closing this now.
