### ISSUE TITLE
Footer links with anchor tag not working

### ISSUE THREAD

**Issue by CuriousLearner** [Mozpacers/Mozpacers.github.io#45]
Try to hit a footer link which contains an anchor on the same page and it would fail. Every link goes to # .

Need a fix for this.

**Comment by theaverageguy** [comment]
Assign me this.

**Comment by CuriousLearner** [comment]
@yash14123 You can take this. Please go ahead!

**Comment by manrajgrover** [comment]
They don't even work in Chrome. Can @Mozpacers/contributors confirm this?

**Comment by CuriousLearner** [comment]
Okay, here is what I've been able to debug till now. 

If you move any link say for example I moved about link from footer to above sections and test it, it doesn't work in any section.
As soon as it is placed in download firefox section, it works but instead of pointing to about section it points to slider above it.

**Comment by CuriousLearner** [comment]
This bug is caused with this [commit](https://github.com/Mozpacers/Mozpacers.github.io/commit/665844774cdb1789268d15e231da3afc1a8b2f4f)

It is something with the changes in main js file.

**Comment by CuriousLearner** [comment]
Fixed by @Slayslot via [this](https://github.com/Mozpacers/Mozpacers.github.io/commit/c3dafb3d834892aee16202a4926f1fda51cdd625) and [this](https://github.com/Mozpacers/Mozpacers.github.io/commit/fd10c6bc6fe851d03edf1d0963a132f7dcf3550a) commit.

Thanks for your contributions :)
