### ISSUE TITLE
Footer located too close to the message box in the "Contact us" section. Needs some margining.

### ISSUE THREAD

**Issue by theaverageguy** [Mozpacers/Mozpacers.github.io#46]

**Comment by CuriousLearner** [comment]
If you feel it is, can you please post a screenshot?

**Comment by manrajgrover** [comment]
This only occurs in Chrome

![untitled1212](https://cloud.githubusercontent.com/assets/5673050/12907186/75ea9ba8-cf0e-11e5-9599-4145ea082c38.png)

**Comment by manrajgrover** [comment]
Related to #43 I guess

**Comment by CuriousLearner** [comment]
This is appearing on Chrome, not on Firefox @ManrajGrover

**Comment by manrajgrover** [comment]
That is what I said @CuriousLearner

**Comment by CuriousLearner** [comment]
Duplicate of #43
