### ISSUE TITLE
#48 Grammatical errors in text.!

### ISSUE THREAD

**Issue by theaverageguy** [Mozpacers/Mozpacers.github.io#48]
"""We strongly believe in building up an Open and dynamic community, who will contribute actively to achieve Mozilla’s Mission i.e. Making a better Web. """
Issue : community that NOT community,who

"""Apart from Delhi and NCR , we also propagate the idea of Open source Community and Mozilla in various other North Indian states viz Himachal Pradesh, Rajasthan, Punjab etc, through various workshops, seminars and events."""
Issue : An idea of mozilla makes very less sense. S is small in source while Open and Community have capital letters.

**Comment by CuriousLearner** [comment]
@yash14123 Issue PR

**Comment by CuriousLearner** [comment]
Corrected in this [commit](https://github.com/Mozpacers/Mozpacers.github.io/commit/a3bb89c1eea0eef13472f800bc06b3c0462fa129)
