### ISSUE TITLE
Overlapping text on slide up animation

### ISSUE THREAD

**Issue by theaverageguy** [Mozpacers/Mozpacers.github.io#49]
Hovering mouse on the Mozcoffee event on Oct 5 gives a sliding animation followed by some visible text. The last line has overlapping text.

**Comment by CuriousLearner** [comment]
@yash14123 there is no event for Oct 5 on the site. Can you please post a screenshot as what you're exactly referring to?

**Comment by theaverageguy** [comment]
![overlap](https://cloud.githubusercontent.com/assets/9817962/12905159/dfa06a28-cefa-11e5-876b-85d7734c33b8.PNG)

**Comment by CuriousLearner** [comment]
That's for Oct 3, not on Oct 5. It appears good for me on Firefox. Please specify other details, which browser are you using, which version, how do you re-produce this bug etc.

**Comment by CuriousLearner** [comment]
@Slayslot Take this please?

**Comment by handasolo** [comment]
Can't reproduce. Need more info on how to reproduce @yash14123

**Comment by manrajgrover** [comment]
Same. Cannot reproduce it.

**Comment by vipinkhushu** [comment]
@yash14123  Please provide more info. Like the browser you are using

**Comment by chawlaaditya8** [comment]
Not able to reproduce the bug.
Browsers tested 
  Chrome
  Firefox

**Comment by handasolo** [comment]
Waiting till the weekend @yash14123 . Hope to hear some more details or this is being closed for insufficient information.

**Comment by CuriousLearner** [comment]
Closing this, since we haven't heard from a long time.

If you open an issue, please be there to explain as well. We can't fix it, without your help.

On a second note, if you decide to tell us about how to re-produce, please consider opening this up again.
