### ISSUE TITLE
Contact Us form not properly visible on chrome

### ISSUE THREAD

**Issue by h4xr** [Mozpacers/Mozpacers.github.io#50]
The message textarea and send button aren't properly visible when using chrome
OS: Ubuntu 14.04
Browser: Chromium

![screenshot from 2016-02-09 22 03 14](https://cloud.githubusercontent.com/assets/7107127/12922898/5c8cee16-cf79-11e5-8dda-aacacf8fe99a.png)

**Comment by handasolo** [comment]
@CuriousLearner Didn't you deploy a fix for #43 . And @h4xr this is a duplicate of #43

**Comment by CuriousLearner** [comment]
@Slayslot I've corrected that in firefox mobile, the issue still persist in chrome desktop and mobile browser.

**Comment by CuriousLearner** [comment]
Duplicate of #43
