### ISSUE TITLE
Dotdotdot doesn't seem to be working

### ISSUE THREAD

**Issue by handasolo** [Mozpacers/Mozpacers.github.io#54]
[dotdotdot](http://dotdotdot.frebsite.nl/) doesn't seem to be working as mentioned in the [alpha v3 commit](https://github.com/Mozpacers/Mozpacers.github.io/commit/665844774cdb1789268d15e231da3afc1a8b2f4f). I initialized it properly and I have no idea as to why it is not working.
![screenshot from 2016-02-12 23 16 47](https://cloud.githubusercontent.com/assets/5322472/13015379/b8022f56-d1de-11e5-9c4f-afea71a74c07.png)
As seen in the screenshot, the below text should have been turned into 'Knowlarity Communications, 14th Floor, Building...' instead of getting hidden because of being overflowed

**Comment by manrajgrover** [comment]
I was just going to open this issue.
![untitled213123](https://cloud.githubusercontent.com/assets/5673050/13015517/8e706eb8-d1df-11e5-866c-519d21b6e355.png)

**Comment by handasolo** [comment]
@ManrajGrover Yeah, it's been known to me since [alpha 3](https://github.com/Mozpacers/Mozpacers.github.io/commit/665844774cdb1789268d15e231da3afc1a8b2f4f). Sadly, can't get this to work.

**Comment by chawlaaditya8** [comment]
In this particular case simply changing the venue to Knowlarity Communications, Gurgaon will fix it.
Which would be solution to bug #71 and not to dotdotdot error.

**Comment by handasolo** [comment]
bug #71 is dotdotdot error. If dotdotdot was working as it was supposed to, we won't have a bug #71. And your solution is not a permanent solution although I was planning to work some information on the cards a tad bit smaller and more relevant @chawlaaditya8

**Comment by CuriousLearner** [comment]
@Slayslot IIRC @h4xr was working on this? Is this completed, or still in progress?

**Comment by handasolo** [comment]
Yeah, He's working on this in PR #75

**Comment by mbad0la** [comment]
@Slayslot , i'd like to try to resolve this. Please let me know about the progress?

**Comment by handasolo** [comment]
@h4xr What's your progress on this?

**Comment by handasolo** [comment]
@mbad0la, Since @h4xr has close #75. I would suggest either you two collaborate together or one of you make further progress on this. Either way, you both have to decide mutually.

**Comment by mbad0la** [comment]
@Slayslot i'll just share my developments while trying to resolve the issue locally, so that @h4xr stays in the loop.

**Comment by handasolo** [comment]
@mbad0la Sounds good to me.

**Comment by mbad0la** [comment]
@Slayslot @h4xr i was able to figure out some problems.  
-  The _dotdotdot_ function was being called on DOM elements that might not have been rendered because of the async nature of ajax :  So i shifted the function after successful render of the cards.
- For the _dotdotdot_ function to work, there must be some overflow, which wasn't happening because as there wasn't an explicitly set height, the automatic render made sure nothing overflowed the _ellipsis_ div : so i added the max-height parameter inside the _dotdotdot_ function's argument.
  ![tempdotdotdot](https://cloud.githubusercontent.com/assets/8503331/14251082/dbe98f5c-fa9e-11e5-996b-cd8b66945062.png)

Although this works for my current screen size, i guess the website lacks a bit in responsiveness and we'd have to edit a lot to be able to make sure this functionality doesn't break for all screen sizes.

**Comment by handasolo** [comment]
@mbad0la Can you push it to your fork so that I can take a look?

**Comment by mbad0la** [comment]
@Slayslot have a look at my fork. Just pushed in changes.

**Comment by handasolo** [comment]
Sorry for the delay but setting up the local environment for addons server has been eating up my time. Anyhow, your implementation seems good to me, seeing as it is partial I'm hoping you know where the problems lie. Open a PR with those issues fixed and we can review it further. And please note, before submitting a PR, I see that the previous PR you opened had 7 commits and we squashed them into one on our repo. But your repo has 7 commits as is, this can lead to issues. @CuriousLearner This is a problem from the new squash feature. We might frequently face this.

**Comment by mbad0la** [comment]
@Slayslot  it might be tough for me to solve the issue completely as it might require changes on how certain DOM elements are styled upon screen-size change. I'd love it if someone can help me out with this.  
Will make a PR for this issue. :)

**Comment by handasolo** [comment]
@mbad0la Couldn't see how this was unresponsive in your fork. Maybe, you can show me.

**Comment by CuriousLearner** [comment]
@Slayslot Yes, People need to update their fork once their PR is merged.

**Comment by cosmologist10** [comment]
i am fixing this issue.

**Comment by Shashi96** [comment]
i am working in this issue

**Comment by handasolo** [comment]
@mbad0la is already working on this @TheCOsmOLogISt10 @Shashi96 as you and see on #86

**Comment by CuriousLearner** [comment]
Closing this, fix by @mbad0la through #86
