### ISSUE TITLE
Back-button image is not curved.

### ISSUE THREAD

**Issue by handasolo** [Mozpacers/Mozpacers.github.io#55]
As of [alpha 3](https://github.com/Mozpacers/Mozpacers.github.io/commit/665844774cdb1789268d15e231da3afc1a8b2f4f) we've shifted the back button from pure html and css to a png image. The problem that comes with this is that the image cannot be curved as the button is and hence the button is usable even outside the button. Confusing? see the image below
![screenshot from 2016-02-12 23 20 59](https://cloud.githubusercontent.com/assets/5322472/13015488/6700fd70-d1df-11e5-8272-2fa6f0612a75.png)
I have tried using [clip path](https://developer.mozilla.org/en/docs/Web/CSS/clip-path) and border radius, which should have worked but it didn't.

**Comment by manrajgrover** [comment]
Border Radius is working for me on Firefox.

**Comment by handasolo** [comment]
@ManrajGrover And on chrome?

**Comment by manrajgrover** [comment]
@Slayslot Apologies, its working on Chrome and not on Firefox.

**Comment by manrajgrover** [comment]
Got it to work, basically div as well as image both need to be given `border-bottom-right-radius` property.

**Comment by handasolo** [comment]
Ah, nice. Make a commit and end this :D

**Comment by manrajgrover** [comment]
Sure, in 5 minutes.

**Comment by handasolo** [comment]
Sounds good :+1:

**Comment by manrajgrover** [comment]
Lets close this issue as its fixed now.
