### ISSUE TITLE
Venue location cluttering in event card

### ISSUE THREAD

**Issue by CuriousLearner** [Mozpacers/Mozpacers.github.io#59]
If the location is really long then it clutters on the card as shown in the image below:

![screen shot 2016-02-13 at 01 11 22](https://cloud.githubusercontent.com/assets/8039608/13018423/6219b99a-d1ef-11e5-90d1-5f28fa0673c0.png)

**Comment by handasolo** [comment]
Duplicate of #54

**Comment by CuriousLearner** [comment]
Okay, missed that earlier. Closing this one.
