### ISSUE TITLE
Date in past events is broken

### ISSUE THREAD

**Issue by manrajgrover** [Mozpacers/Mozpacers.github.io#61]
![untitled22222](https://cloud.githubusercontent.com/assets/5673050/13018879/3ba98756-d1f2-11e5-9548-85043e46bcfb.png)

**Comment by handasolo** [comment]
Damn missed out a line while making the code modular

**Comment by handasolo** [comment]
check now @ManrajGrover

**Comment by CuriousLearner** [comment]
@Slayslot @ManrajGrover Checked and working. Closing this now.
