### ISSUE TITLE
Contact us send button not properly aligned

### ISSUE THREAD

**Issue by handasolo** [Mozpacers/Mozpacers.github.io#63]
Contact us send button is not properly aligned on mobile. 
Device: Moto G 2014 running CM13 nightly
Browser: CM13 browser
![screenshot_20160213-164510](https://cloud.githubusercontent.com/assets/5322472/13027361/2df4d4e6-d272-11e5-9b00-71cd1be49ede.png)

**Comment by deepakpathania-zz** [comment]
Fixed. Pull request created, please review.

**Comment by handasolo** [comment]
@deepakpathania Will take a look.

**Comment by deepakpathania-zz** [comment]
Fixed. Pull request created on develop branch. Unnecessary spaces removed. Please review.

![send_button](https://cloud.githubusercontent.com/assets/15071438/13086062/6da8dec4-d507-11e5-8e81-d49348dac976.jpg)

**Comment by deepakpathania-zz** [comment]
Fixed on both lg and xs screen sizes. #76 created. Please review.

![sendbutton_desktop](https://cloud.githubusercontent.com/assets/15071438/13150622/89e862f4-d68c-11e5-91d8-a81855e84efe.jpg)

![sendbutton_mobile](https://cloud.githubusercontent.com/assets/15071438/13150638/98f0a86a-d68c-11e5-993c-82de0742eb5f.jpg)

**Comment by handasolo** [comment]
Fixed by @deepakpathania
