### ISSUE TITLE
Footer overflowing on mobile

### ISSUE THREAD

**Issue by handasolo** [Mozpacers/Mozpacers.github.io#64]
Footer seems to overflow on mobile.
Device: Moto G 2014 running CM13 nightly
Browser: CM13 browser
![screenshot_20160213-164515](https://cloud.githubusercontent.com/assets/5322472/13027367/6ba77500-d272-11e5-984b-591eec6d050c.png)

**Comment by akanshgulati** [comment]
Submitted the fork for it. Please review.

**Comment by handasolo** [comment]
@akanshgulati Will take a look.

**Comment by handasolo** [comment]
@akanshgulati Seems good. I don't know about the hover color though.

**Comment by cosmologist10** [comment]
me and vishal thadari both are working on it.

**Comment by CuriousLearner** [comment]
Seems to work, let's close
cc @Slayslot 

Thanks @TheCOsmOLogISt10

**Comment by handasolo** [comment]
Yeah, fix was deployed. Forgot to close this.
