### ISSUE TITLE
[CHROME ONLY] Unsupported Characters In Blog

### ISSUE THREAD

**Issue by vipinkhushu** [Mozpacers/Mozpacers.github.io#65]

**Comment by vipinkhushu** [comment]
![moz blog bug](https://cloud.githubusercontent.com/assets/11455744/13032800/27c3edcc-d327-11e5-97e6-5bbcb31663bf.png)
Steps To Reproduce:-
1. Open http://mozpacers.org/blog using google chrome

**Comment by handasolo** [comment]
Can't reproduce @vipinkhushu

**Comment by vipinkhushu** [comment]
Try windows

**Comment by handasolo** [comment]
Alright, let me check that.

**Comment by vipinkhushu** [comment]
Any updates?

**Comment by handasolo** [comment]
Didn't get to boot into Windows. Will definitely update tonight. Need to transfer songs to my phone so I'll be on windows :P

**Comment by CuriousLearner** [comment]
This is wrong way to report bugs, you should be reporting bugs to the dedicated repo not randomly anywhere.

Blog repo is here: https://github.com/Mozpacers/blog/

Open up this issue there.
