### ISSUE TITLE
Shift backend to seperate repository

### ISSUE THREAD

**Issue by CuriousLearner** [Mozpacers/Mozpacers.github.io#79]
In order to efficiently manage things, the back-end should be moved to a seperate repository. 

This would also help in later interfacing it with other projects.

**Comment by handasolo** [comment]
Sounds good to me

**Comment by CuriousLearner** [comment]
I've shifted the API to a seperate repo. Now there are essentially two questions to be answered.
- Should we also take the previous history (only of back-end obviously) in the new repository
- What happens to the structure of this repository
  - Should we just remove the src/server/ part?
  - Should we re-structure it in a different manner all together?

Need Inputs @Slayslot

**Comment by handasolo** [comment]
@CuriousLearner Yes we should take the previous history. We should re-structure since the current structure is based on both back-end and front-end being on the same repository.

**Comment by CuriousLearner** [comment]
Okay, so how should the new structure go?

src/ and then all the files? Basically pulling out everything from src/client to src/
Does that sound good? Or you suggest some other alternative?

**Comment by handasolo** [comment]
That sounds good enough to me

**Comment by CuriousLearner** [comment]
Sure, I'll do that.
For the history, we'll create the issue in that repo and then progress. Actually have to see that no sensitive information is passed in the that repo which may have been done due to hosting on heroku.
