### ISSUE TITLE
The website is shifted to the left.

### ISSUE THREAD

**Issue by theaverageguy** [Mozpacers/Mozpacers.github.io#80]
Browser : Chrome Version 38.0.2125.111 m
![d](https://cloud.githubusercontent.com/assets/9817962/13391421/66d9d934-defa-11e5-9a58-2b7bc8b0516d.png)

There is a lot of space in the right.

**Comment by handasolo** [comment]
Can't reproduce. Chrome version 48.0.2564.109.

**Comment by handasolo** [comment]
P.S. @yash14123 please respond to the previous issue you've opened.

**Comment by CuriousLearner** [comment]
Negative. I cannot reproduce it either.

Can you please provide more details @yash14123

**Comment by handasolo** [comment]
Closed for lack of information. @theaverageguy please reopen if you feel the need to.
