### ISSUE TITLE
Buttons on Event Cards need better transitions

### ISSUE THREAD

**Issue by mbad0la** [Mozpacers/Mozpacers.github.io#84]
![pacerbug1](https://cloud.githubusercontent.com/assets/8503331/14216877/b76953ca-f868-11e5-8ff2-45a60025c1f4.gif)
Buttons at the moment are quite broken, collapsing on hover out and transitioning inside the cards at a z-index greater than the card's box.  
I guess a better implementation will look a lot more cleaner and smooth.

**Comment by CuriousLearner** [comment]
Hi @mbad0la Thanks for the issue. Would you like to take this up?

**Comment by handasolo** [comment]
@mbad0la So, you mean the transition of the buttons need to be better?

**Comment by mbad0la** [comment]
@CuriousLearner, sure.

**Comment by mbad0la** [comment]
@Slayslot, yeah the overflow during the transition and the sudden collapse. I suppose it would look much better then.

**Comment by handasolo** [comment]
@mbad0la Alright, then I suggest you change the issue title to 'Buttons on Event Cards need better transitions'. And yes, would love to see a PR from you.

**Comment by CuriousLearner** [comment]
Closing this now! Fixed by @mbad0la in #85
